### ISSUE TITLE
RISC-V GCC Toolchain question

### ISSUE THREAD

**Issue by sunnystormy** [dan-rodrigues/icestation-32#1]
Hello! I love this project and think that its a wonderful idea! I am about to download the RISC-V toolchain from its repo, and I'm wondering if you mean for users to build the "newlib" version of the toolchain? Throughout the documentation for this repo you say "GNU RISC-V" toolchain, but that still doesn't specify whether its the 'newlib' build, or the 'Linux' build. Would you mind clearing this up?

Thank you for your help!

**Comment by dan-rodrigues** [comment]
Hi, short answer: the newlib version. It should be configured with `--enable-multilibs` assuming that isn’t the default already.

Longer answer: The picorv32 repo [includes some `make` targets](https://github.com/cliffordwolf/picorv32#building-a-pure-rv32i-toolchain) to simplify the build and install. The demos in this project only use the `RV32I` ISA. Trying to build the toolchain on a case-insensitive filesystem will probably not work though, so anyone trying it on a default MacOS installation for example will likely have problems. If there are issues preventing builds from source, I can confirm that at least Darwin binaries in [this xpack release](https://github.com/xpack-dev-tools/riscv-none-embed-gcc-xpack/releases/tag/v8.3.0-1.1) work fine. I'll update the README with this info too.

**Comment by dan-rodrigues** [comment]
I added some [better instructions to the README](https://github.com/dan-rodrigues/icestation-32#prerequisites) a while ago but forgot to revisit this issue. I'll close this as the revised docs should be more helpful now. New issues welcome if any other docs are unclear or lacking.
