### ISSUE TITLE
make icebreaker_prog failed

### ISSUE THREAD

**Issue by wuxx** [dan-rodrigues/icestation-32#4]
Hi, the make icebreaker_prog cmd failed, it seems that the LCs is exceed 5280. 
I use the 
Yosys 0.9+2406 (git sha1 819f1d8c, clang 6.0.0-1ubuntu2 -fPIC -Os)
and
nextpnr-ice40 -- Next Generation Place and Route (git sha1 abfe31d)

----------------------
Info: Device utilisation:
Info:            ICESTORM_LC:  5306/ 5280   100%
Info:           ICESTORM_RAM:    30/   30   100%
Info:                  SB_IO:    34/   96    35%
Info:                  SB_GB:     5/    8    62%
Info:           ICESTORM_PLL:     1/    1   100%
Info:            SB_WARMBOOT:     0/    1     0%
Info:           ICESTORM_DSP:     7/    8    87%
Info:         ICESTORM_HFOSC:     0/    1     0%
Info:         ICESTORM_LFOSC:     0/    1     0%
Info:                 SB_I2C:     0/    2     0%
Info:                 SB_SPI:     0/    2     0%
Info:                 IO_I3C:     0/    2     0%
Info:            SB_LEDDA_IP:     0/    1     0%
Info:            SB_RGBA_DRV:     0/    1     0%
Info:         ICESTORM_SPRAM:     4/    4   100%

Info: Placed 38 cells based on constraints.
Info: Creating initial analytic placement for 4660 cells, random placement wirelen = 130669.
Info:     at initial placer iter 0, wirelen = 2202
Info:     at initial placer iter 1, wirelen = 2095
Info:     at initial placer iter 2, wirelen = 2275
Info:     at initial placer iter 3, wirelen = 2044
Info: Running main analytical placer.
ERROR: Failed to expand region (0, 0) |_> (25, 31) of 5305 ICESTORM_LCs
3 warnings, 1 error
Makefile:103: recipe for target 'icebreaker.asc' failed
make: *** [icebreaker.asc] Error 255
---------------------
and here is the detail log
[1.log](https://github.com/dan-rodrigues/icestation-32/files/5391335/1.log)

**Comment by dan-rodrigues** [comment]
Hi, there’s big differences in LC usage between Yosys commits. Here’s what I’m using:

` Yosys 0.9+3537 (git sha1 c75d8c74, clang 11.0.3 -fPIC -Os)`

`make icebreaker` result:

```
Info: Device utilisation:
Info: 	         ICESTORM_LC:  4790/ 5280    90%
```

Trying it with Yosys built from `c75d8c74` should fix this. I’ll add a README section with confirmed working commits of tools to help anyone building from source.

**Comment by wuxx** [comment]
after update to the latest yosys (Yosys 0.9+3624 (git sha1 4c925a32, clang 6.0.0-1ubuntu2 -fPIC -Os)
), now bitstream build ok, thank you dan!
