### ISSUE TITLE
"FORCE_FAST_CPU" parameter still mentioned in README

### ISSUE THREAD

**Issue by vmedea** [dan-rodrigues/icestation-32#5]
The `FORCE_FAST_CPU` parameter mentioned in the README doesn't exist anymore. I suppose this is `ENABLE_FAST_CPU` now?

Effectively at least. Looking at the git history the logic around it also slightly changed, the new parameter only exists in the toplevel for the ULX3S and is always disabled for Icebreaker.

In any case, I think this needs a documentation update.

**Comment by dan-rodrigues** [comment]
Thanks for spotting this. This and a few other things in the README need updating. Will fix these soon.

**Comment by dan-rodrigues** [comment]
The updates in https://github.com/dan-rodrigues/icestation-32/commit/09092e22ed0b36919571a6de1592116468bf5e0e should address this so I'll close this issue. New issues on any other documentation problems are welcome. `ENABLE_FAST_CPU` is documented along with the reason it's only surfaced as a parameter in the ULX top level. The software made so far assumes the default "slow" config with the CPU running at half the video clock, so both iCEBreaker and ULX behave the same. I didn't spot any issues running the demos on the fast config but I've not tested it extensively.

**Comment by vmedea** [comment]
Yes this is much clearer thank you!
